### ISSUE TITLE
Installed but disabled module causes the saving of quote to malfunction

### ISSUE THREAD

**Issue by TobiasLufinity** [SwedbankPay/swedbank-pay-magento2-checkout#33]
If the module is installed but disabled a customer can't add products to the cart.
This is due to a incorrect plugin in the code.

The class SwedbankPay\Checkout\Plugin\QuoteRepositoryPlugin contains the plugin aroundSave which returns null if the module is disabled.
This need to let the function to proceed and this is done by returning $proceed($quote).

So 
`        
if (!$this->config->isActive()) {
    return null;
}
`
needs to be replaced with
`        
if (!$this->config->isActive()) {
    return $preceed($quote);
}
`

**Comment by asbjornu** [comment]
A pull request with https://github.com/evalentgroup/swedbank-pay-magento2-checkout/commit/577073d3c2a6cf8a958a169fdf9f36548fcfc96a would be highly appreciated, @TobiasLufinity!
